name: Build and Publish Docker Image

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ env.REGISTRY }}/<user>/<repo>:latest  # podmień <user> i <repo>

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU (for multi-arch build, opcjonalnie)
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Budowanie obrazu i testowanie
    - name: Build Docker image
      run: docker build -t sjuprojekt .

    - name: Run test script inside container
      run: docker run --rm sjuprojekt python /home/vscode/workspace/test.py

    # Logowanie do GitHub Container Registry (GHCR)
    - name: Log into GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Tagowanie i push obrazu do rejestru
    - name: Tag Docker image
      run: docker tag sjuprojekt ${{ env.IMAGE_NAME }}

    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }}
