name: Build and Publish Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t sjuprojekt .

      - name: Copy test script
        run: cp test.py test_inside.py

      - name: Run test inside container
        run: docker run --rm -v ${{ github.workspace }}/test_inside.py:/test.py sjuprojekt python /test.py

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker tag sjuprojekt $IMAGE_ID
          docker push $IMAGE_ID
